import {Card} from '../classes/Card';

export const CARDS :Card[]=[
    {
        id: 1,
        city: 'london',
        image: '/assets/images/london1.jpg',
        backside: 'assets/images/backside.jpg',
        show: false,
    },
    {
        id: 2,
        city: 'london',
        image: '/assets/images/london2.jpg',
        backside: 'assets/images/backside.jpg',
        show: false,
    },
    {
        id: 3,
        city: 'london',
        image: '/assets/images/london3.jpg',
        backside: 'assets/images/backside.jpg',
        show: false,
    },
    {
        id: 4,
        city: 'london',
        image: '/assets/images/london4.jpg',
        backside: 'assets/images/backside.jpg',
        show: false,
    },
    {
        id: 5,
        city: 'london',
        image: '/assets/images/london5.jpg',
        backside: 'assets/images/backside.jpg',
        show: false,
    },
    {
        id: 6,
        city: 'london',
        image: '/assets/images/london6.jpg',
        backside: 'assets/images/backside.jpg',
        show: false,
    },
    {
        id: 7,
        city: 'london',
        image: '/assets/images/london7.jpg',
        backside: 'assets/images/backside.jpg',
        show: false,
    },
    {
        id: 8,
        city: 'london',
        image: '/assets/images/london8.jpg',
        backside: 'assets/images/backside.jpg',
        show: false,
    },
    {
        id: 1,
        city: 'paris',
        image: '/assets/images/paris1.jpg',
        backside: '/assets/images/backside.jpg',
        show: false,
    },
    {
        id: 2,
        city: 'paris',
        image: '/assets/images/paris2.jpg',
        backside: '/assets/images/backside.jpg',
        show: false,
    },
    {
        id: 3,
        city: 'paris',
        image: '/assets/images/paris3.jpg',
        backside: '/assets/images/backside.jpg',
        show: false,
    },
    {
        id: 4,
        city: 'paris',
        image: '/assets/images/paris4.jpg',
        backside: '/assets/images/backside.jpg',
        show: false,
    }, {
        id: 5,
        city: 'paris',
        image: '/assets/images/paris5.jpg',
        backside: '/assets/images/backside.jpg',
        show: false,
    }, {
        id: 6,
        city: 'paris',
        image: '/assets/images/paris6.jpg',
        backside: '/assets/images/backside.jpg',
        show: false,
    }, {
        id: 7,
        city: 'paris',
        image: '/assets/images/paris7.jpg',
        backside: '/assets/images/backside.jpg',
        show: false,
    },
    {
        id: 8,
        city: 'paris',
        image: '/assets/images/paris8.jpg',
        backside: '/assets/images/backside.jpg',
        show: false,
    },
    {
        id: 1,
        city: 'madrid',
        image: '/assets/images/madrid1.jpg',
        backside: '/assets/images/backside.jpg',
        show: false,
    },
    {
        id: 2,
        city: 'madrid',
        image: '/assets/images/madrid2.jpg',
        backside: '/assets/images/backside.jpg',
        show: false,
    },
    {
        id: 3,
        city: 'madrid',
        image: '/assets/images/madrid3.jpg',
        backside: '/assets/images/backside.jpg',
        show: false,
    },
    {
        id: 4,
        city: 'madrid',
        image: '/assets/images/madrid4.jpg',
        backside: '/assets/images/backside.jpg',
        show: false,
    }, {
        id: 5,
        city: 'madrid',
        image: '/assets/images/madrid5.jpg',
        backside: '/assets/images/backside.jpg',
        show: false,
    }, {
        id: 6,
        city: 'madrid',
        image: '/assets/images/madrid6.jpg',
        backside: '/assets/images/backside.jpg',
        show: false,
    }, {
        id: 7,
        city: 'madrid',
        image: '/assets/images/madrid7.jpg',
        backside: '/assets/images/backside.jpg',
        show: false,
    },
    {
        id: 8,
        city: 'madrid',
        image: '/assets/images/madrid8.jpg',
        backside: '/assets/images/backside.jpg',
        show: false,
    },
    {
        id: 1,
        city: 'vienna',
        image: '/assets/images/vienna1.jpg',
        backside: '/assets/images/backside.jpg',
        show: false,
    },
    {
        id: 2,
        city: 'vienna',
        image: '/assets/images/vienna2.jpg',
        backside: '/assets/images/backside.jpg',
        show: false,
    },
    {
        id: 3,
        city: 'vienna',
        image: '/assets/images/vienna3.jpg',
        backside: '/assets/images/backside.jpg',
        show: false,
    },
    {
        id: 4,
        city: 'vienna',
        image: '/assets/images/vienna4.jpg',
        backside: '/assets/images/backside.jpg',
        show: false,
    }, {
        id: 5,
        city: 'vienna',
        image: '/assets/images/vienna5.jpg',
        backside: '/assets/images/backside.jpg',
        show: false,
    }, {
        id: 6,
        city: 'vienna',
        image: '/assets/images/vienna6.jpg',
        backside: '/assets/images/backside.jpg',
        show: false,
    }, {
        id: 7,
        city: 'vienna',
        image: '/assets/images/vienna7.jpg',
        backside: '/assets/images/backside.jpg',
        show: false,
    },
    {
        id: 8,
        city: 'vienna',
        image: '/assets/images/vienna8.jpg',
        backside: '/assets/images/backside.jpg',
        show: false,
    },
]